'use client';

import React, { useRef } from 'react';
import { 
  Printer, 
  Download, 
  ShieldCheck, 
  FileText, 
  CheckCircle, 
  AlertTriangle,
  QrCode,
  Lock,
  X
} from 'lucide-react';
import { DEMO_FORENSIC_ANALYSIS, DEMO_ASSET, DEMO_DNA, DEMO_PROVENANCE } from '@/lib/data';

export default function ForensicReportSection() {
  const reportRef = useRef<HTMLDivElement | null>(null);

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const content = `ARGOS AI DIGITAL MEDIA FORENSIC REPORT\n\n` +
      `Case ID: #ARG-8291\nAsset ID: ${DEMO_ASSET.id}\nOriginal Fingerprint (SHA-256): ${DEMO_DNA.sha256Hash}\n` +
      `Provenance: C2PA v2.1 Claim Valid\nWatermark: ACTIVE (Spread-spectrum detected 88%)\n` +
      `Overall Risk Score: 93.0% (HIGH RISK MANIPULATION)\n\n` +
      `Suspicious Timestamps:\n- 00:07 - 00:14 (Suspicious phoneme shift)\n- 00:14 - 00:18 (HIGH RISK lip-sync anomaly +320ms)\n- 00:18 - 00:26 (HIGH RISK vocoder audio clone)\n\n` +
      `Generated by ARGOS AI Forensics Core v3.4. Cryptographically signed.`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ARGOS_FORENSIC_REPORT_ARG-8291.txt`;
    a.click();
  };

  return (
    <section id="forensic-report-section" className="w-full py-20 px-4 lg:px-8 bg-[#F7F3E8] border-b-[3px] border-[#111111]">
      <div className="max-w-7xl mx-auto">
        
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-10 gap-6 border-b-[3px] border-[#111111] pb-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#111111] text-[#F4CD3F] border-[2px] border-[#111111] font-mono text-xs font-bold uppercase tracking-wider mb-3">
              09 // FORMAL EVIDENCE DOSSIER
            </div>
            <h2 className="text-3xl sm:text-5xl font-black uppercase tracking-tight text-[#111111] font-display">
              FORENSIC DOSSIER
            </h2>
          </div>
          
          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-[#EFD99C] hover:bg-white text-black border-[2px] border-[#111111] brutal-btn font-mono text-xs font-bold flex items-center gap-1.5"
            >
              <Printer className="w-3.5 h-3.5" />
              PRINT DOSSIER
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-[#F4CD3F] hover:bg-[#ffe066] text-black border-[2px] border-[#111111] brutal-btn font-mono text-xs font-black flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              [ GENERATE FORENSIC REPORT ]
            </button>
          </div>
        </div>

        {/* The Realistic PDF Preview Document */}
        <div 
          ref={reportRef} 
          className="bg-white border-[4px] border-[#111111] brutal-shadow-xl p-8 sm:p-12 max-w-4xl mx-auto text-[#111111] font-mono text-xs"
        >
          {/* Official Forensic Header */}
          <div className="border-b-[3px] border-[#111111] pb-6 mb-6">
            <div className="flex items-start justify-between">
              <div>
                <div className="text-2xl sm:text-3xl font-black uppercase tracking-tight font-display text-[#111111]">
                  ARGOS AI
                </div>
                <div className="text-xs sm:text-sm font-black uppercase tracking-widest text-[#844469] mt-0.5">
                  DIGITAL MEDIA FORENSIC REPORT
                </div>
                <div className="text-[10px] text-gray-500 mt-1">
                  SOVEREIGN CYBER FORENSICS & PROVENANCE CERTIFICATION
                </div>
              </div>

              {/* Security Seal & QR Code simulation */}
              <div className="flex flex-col items-end">
                <div className="w-12 h-12 border-[2px] border-[#111111] bg-[#F4CD3F] flex items-center justify-center p-1">
                  <div className="w-full h-full border border-[#111111] flex items-center justify-center font-black text-[9px]">
                    SEAL
                  </div>
                </div>
                <span className="text-[9px] text-gray-500 mt-1 font-bold">DOC REF: #9904-B</span>
              </div>
            </div>
          </div>

          {/* Dossier Meta Table */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-4 bg-[#F7F3E8] border-[2px] border-[#111111] mb-6 text-[11px]">
            <div>
              <div className="text-gray-500 uppercase text-[9px] font-bold">Case ID</div>
              <div className="font-black text-[#111111]">#ARG-8291</div>
            </div>
            <div>
              <div className="text-gray-500 uppercase text-[9px] font-bold">Asset ID</div>
              <div className="font-black text-[#844469]">{DEMO_ASSET.id}</div>
            </div>
            <div>
              <div className="text-gray-500 uppercase text-[9px] font-bold">Provenance Status</div>
              <div className="font-black text-[#8BCF9B]">C2PA v2.1 VALID ✓</div>
            </div>
            <div>
              <div className="text-gray-500 uppercase text-[9px] font-bold">Watermark Status</div>
              <div className="font-black text-[#8BCF9B]">ACTIVE (88% EXTRACTED)</div>
            </div>
          </div>

          {/* Original Fingerprint Section */}
          <div className="mb-6 p-3 bg-white border border-[#111111]">
            <div className="text-[10px] font-black uppercase text-[#111111] mb-1">
              Original Cryptographic Root Fingerprint:
            </div>
            <div className="text-[10px] text-gray-800 break-all bg-gray-100 p-1.5 border border-gray-300">
              SHA-256: {DEMO_DNA.sha256Hash}
            </div>
          </div>

          {/* Detection Scores & Model Agreement */}
          <div className="mb-6 border-[2px] border-[#111111] p-4 bg-white">
            <div className="text-xs font-black uppercase text-[#111111] pb-2 border-b border-[#111111]/20 mb-3 flex items-center justify-between">
              <span>MULTI-MODEL FORENSIC ANOMALY SCORES</span>
              <span className="text-[#D95D5D] font-black">OVERALL RISK: 93.0% [HIGH RISK]</span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center mb-3">
              <div className="p-2 bg-[#F7F3E8] border border-[#111111]">
                <div className="text-[9px] uppercase font-bold text-gray-600">Lip-Sync Anomaly</div>
                <div className="text-lg font-black text-[#D95D5D]">91.0%</div>
              </div>
              <div className="p-2 bg-[#F7F3E8] border border-[#111111]">
                <div className="text-[9px] uppercase font-bold text-gray-600">Visual Anomaly</div>
                <div className="text-lg font-black text-[#D95D5D]">74.0%</div>
              </div>
              <div className="p-2 bg-[#F7F3E8] border border-[#111111]">
                <div className="text-[9px] uppercase font-bold text-gray-600">Audio Anomaly</div>
                <div className="text-lg font-black text-[#D95D5D]">62.0%</div>
              </div>
              <div className="p-2 bg-[#F7F3E8] border border-[#111111]">
                <div className="text-[9px] uppercase font-bold text-gray-600">Temporal Anomaly</div>
                <div className="text-lg font-black text-[#D95D5D]">88.0%</div>
              </div>
            </div>

            <div className="flex justify-between items-center text-[10px] text-gray-700 pt-2 border-t border-gray-200">
              <span>Model Agreement: <strong>4 / 4 Consensus Models</strong></span>
              <span>Temporal Mismatch: <strong className="text-[#D95D5D]">+320ms</strong></span>
              <span>Classification: <strong className="text-[#D95D5D]">SYNTHETIC MANIPULATION</strong></span>
            </div>
          </div>

          {/* Suspicious Timestamps & Analysis Timeline */}
          <div className="mb-6">
            <div className="text-xs font-black uppercase text-[#111111] mb-2">
              SUSPICIOUS TIMESTAMPS & TIMELINE DELTA:
            </div>
            <div className="space-y-1 text-[11px]">
              <div className="p-2 bg-[#8BCF9B]/20 border border-[#8BCF9B] flex justify-between">
                <span>00:00 – 00:07</span>
                <span className="font-bold text-[#8BCF9B]">BASELINE AUTHENTIC SPEECH [8% RISK]</span>
              </div>
              <div className="p-2 bg-[#F4CD3F]/20 border border-[#F4CD3F] flex justify-between">
                <span>00:07 – 00:14</span>
                <span className="font-bold text-[#F4CD3F]">SUSPICIOUS: VISEME PHONEME LAG INITIATES [42% RISK]</span>
              </div>
              <div className="p-2 bg-[#D95D5D]/30 border border-[#D95D5D] flex justify-between">
                <span>00:14 – 00:18</span>
                <span className="font-black text-[#D95D5D]">CRITICAL: SYNTHETIC LIP WARP & +320ms DESYNC [93% RISK]</span>
              </div>
              <div className="p-2 bg-[#D95D5D]/20 border border-[#D95D5D] flex justify-between">
                <span>00:18 – 00:26</span>
                <span className="font-black text-[#D95D5D]">HIGH RISK: CLONED AUDIO SPECTRAL CUTOFF [86% RISK]</span>
              </div>
              <div className="p-2 bg-[#8BCF9B]/20 border border-[#8BCF9B] flex justify-between">
                <span>00:26 – 00:32</span>
                <span className="font-bold text-[#8BCF9B]">REVERTS TO AUTHENTIC OUTRO [12% RISK]</span>
              </div>
            </div>
          </div>

          {/* Evidence Frames Annex */}
          <div className="mb-6">
            <div className="text-xs font-black uppercase text-[#111111] mb-2">
              EXHIBIT ANNEX: EVIDENCE FRAMES
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {DEMO_FORENSIC_ANALYSIS.evidenceFrames.map((f, i) => (
                <div key={i} className="border border-[#111111] p-2 bg-[#F7F3E8] text-[10px]">
                  <div className="font-bold text-[#D95D5D] mb-1">
                    FRAME #{f.frameNumber} [{f.timestamp}]
                  </div>
                  <div className="font-black text-black mb-1">{f.label}</div>
                  <div className="text-gray-600 leading-tight">{f.description}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Legal Certification Footer */}
          <div className="pt-4 border-t-[2px] border-[#111111] flex flex-col sm:flex-row justify-between items-start sm:items-center text-[9px] text-gray-500 gap-2">
            <div>
              CERTIFIED DIGITALLY BY ARGOS FORENSICS ENGINE V3.4 // C2PA LEDGER DID:did:argos:sig-7b2f901a
            </div>
            <div className="font-bold text-[#111111]">
              VERIFICATION HASH: e93f608b...a991
            </div>
          </div>

        </div>

      </div>
    </section>
  );
}
