from datetime import datetime
from fastapi import APIRouter
from app.core.mock_data import (
    SAMPLE_REPORT,
    SAMPLE_FORENSIC_ANALYSIS,
    SAMPLE_DNA,
    SAMPLE_PROVENANCE,
    DEMO_ASSET_ID
)

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.get("/{report_id}")
def get_forensic_report(report_id: str):
    """
    Get full structured forensic report for rendering or printing.
    """
    analysis = SAMPLE_FORENSIC_ANALYSIS[DEMO_ASSET_ID]
    dna = SAMPLE_DNA[DEMO_ASSET_ID]
    provenance = SAMPLE_PROVENANCE[DEMO_ASSET_ID]
    
    return {
        **SAMPLE_REPORT,
        "asset_id": DEMO_ASSET_ID,
        "original_fingerprint": dna["sha256_hash"],
        "visual_dna": dna["visual_dna_signature"],
        "audio_dna": dna["audio_dna_signature"],
        "temporal_dna": dna["temporal_dna_signature"],
        "provenance_claim": provenance["c2pa_manifest_id"],
        "watermark_status": "VALID & ACTIVE (Extraction confidence: 99.4%)",
        "overall_risk_score": analysis["overall_manipulation_risk"],
        "anomaly_scores": {
            "lip_sync_anomaly": analysis["lip_sync_anomaly"],
            "visual_anomaly": analysis["visual_anomaly"],
            "audio_anomaly": analysis["audio_anomaly"],
            "temporal_anomaly": analysis["temporal_anomaly"]
        },
        "model_agreement": analysis["model_agreement"],
        "temporal_mismatch": f"+{analysis['temporal_mismatch_ms']}ms",
        "suspicious_timestamps": ["00:07 - 00:14 (Suspicious)", "00:14 - 00:18 (HIGH RISK)", "00:18 - 00:26 (HIGH RISK)"],
        "evidence_frames": analysis["evidence_frames"],
        "explanation": analysis["explanation"],
        "legal_notice": "Generated by ARGOS AI. This report provides scientific forensic indicators and cryptographic provenance assertions. Coverage reflects monitored and indexed sources."
    }
